language: rust
os:
- linux
- windows
rust:
- stable
jobs:
  allow_failures:
  - rust: nightly
  fast_finish: true
before_install:
- if [ "$TRAVIS_OS_NAME" = "windows" ]; then export LIB="./lib"; fi
install:
- cargo build --release
script:
- cargo test --release
addons:
  apt:
    packages:
    - libsdl2-dev
    - libsdl2-image-dev
    - libsdl2-mixer-dev
    - libsdl2-ttf-dev
before_deploy:
- |-
  if [ "$TRAVIS_OS_NAME" = "windows" ]; then
    mkdir super-jeff
    cp target/release/super-jeff.exe ./super-jeff
    cp -r assets ./super-jeff
    cp lib/*.{dll,txt} ./super-jeff
    ls -l super-jeff
    tar -cavf super-jeff.zip super-jeff
  fi
  if [ "$TRAVIS_OS_NAME" = "linux" ]; then
    zip -j super-jeff.zip target/release/super-jeff
    zip -r super-jeff.zip assets
  fi
deploy:
  provider: releases
  file: super-jeff.zip
  skip_cleanup: true
  draft: true
  api_key:
    secure: "ky6DJ+k4etGHb3/glW30XlRkucisSQ2GjGyYUG4GclGOvKt2/uEQK+S5n9n8fHTPxx/1m5mNhTLfmsSVxJDs6kHT2o2kEOgk60acHKhjAU/zx83HBF1ngF0G0wbDrfMAe4xN4ktxXv/J8x3E23snCY8tESIaIUeV/sgvUENqvYylXAw9x45OGS79JIcaj2tBncaB/+BYd+sbcdvKw6HPyfNQ6qgjGYz0cQLKxhk7+dwANg/Dmbbhjlxj90YNQN2Y2mxvlAdSqlfRgkxXnMWo5dzr4ayyD1Qpo3VcTcmGMrySDM3vXFSEz9pfdMZHN924+OHVdiXNeCiKfxHNEDAmDQC+i0S4lZJ3J4DSyNJ+rqkYDEI4QGbDVocKGaJERo/Hr8vwWaThRa+xMRpCgusIPUxUZmOYVNL+R2A9Zk59zr0tMaq8muiuqiUHeMyD5xMEtm8yE07zwwHLxcGMXiL5cHI4LCWoFCMrSifDpwBwsaGcjEpu+SInAbxe8nXTqmy5ETSwC7s5tgfUSqQLUkZlN3OoVseJ8XnIK5HuKzifXm47Ifr5kWcpdC6hnrKrbdDcVfxoUYbQ0XbmdMKhyKZmT8/aWbcFK9bDDnpP0N/uSQWBA4o6cW90sZzvNo7cI31OVeRrSdxfKIWncegFSz5cXSWenLWLMQSvIMkADfDkFPQ="
