language: rust
os:
- linux
- windows
rust:
- stable
jobs:
  allow_failures:
  - rust: nightly
  fast_finish: true
before_install:
- if [ "$TRAVIS_OS_NAME" = "windows" ]; then export LIB="./lib"; fi
script:
- cargo build --verbose
- cargo test --verbose
- cargo build --release
addons:
  apt:
    packages:
    - libsdl2-dev
    - libsdl2-image-dev
    - libsdl2-mixer-dev
    - libsdl2-ttf-dev
before_deploy:
- |-
  if [ "$TRAVIS_OS_NAME" = "windows" ]; then
    mkdir super-jeff
    cp target/release/super-jeff.exe ./super-jeff
    cp -r assets ./super-jeff
    cp lib/*.{dll,txt} ./super-jeff
    ls -l super-jeff
    tar -cavf super-jeff.zip super-jeff
  fi
  if [ "$TRAVIS_OS_NAME" = "linux" ]; then
    mkdir super-jeff
    cp target/release/super-jeff ./super-jeff
    cp -r assets ./super-jeff
    zip -r super-jeff.zip super-jeff
  fi
deploy:
  provider: releases
  file: super-jeff.zip
  skip_cleanup: true
  draft: true
  api_key:
    secure: LNa+7gm7mcgHalxrm6L20yKUfKkuvs0BCKWvWYIcyz62SbwFMmbV0DEg49HoQdGPV1HPAfF31pc3Gl04WL5JHA4xTRYdcwFUMEGmc/HCyiscNcoijWefN5uA7ND+n5tgkR+JEgg/OAQQB4n0BciOM9quDw0z6awlx9Y2qJnb5s17odLu9GdqYJlN+cfOw47d40CPHt3wQ9527iHh+fR5HRFyQsM7S3B07gypoNEy2jkFK6OsCSeDJFybkJEe9xoEgTlfuDh/2zLrkuj4eYILbSOBeoaBtJEgVL8mbMqG9bU9+yvWmmZ30L7Kq0i2/rENjv5TZObjQFM2gwkGE95PiyjfVFJ6wRB9NqrJIQKZzKUY95jIk5FpGqS7lAbJdXYYJrJ02UfZn2zlcBcTSpyaYQJAqkBsKNiiYnvci7uDf9OUrv80zeToNS3MlQhkM1FvixG9E0PSm+iPXo3aIRanzPn9gNoLQUvgYnEPW7SDraJUFzCt2BF8cszZz/GqDZpt0fYrI143tdICnVBREbAP8u/H69asOy9zWTE/J3Qa41nh3sykjLzZDJWa0lu8Vp0cz1ZJCoMQN/5Sqil0pumpR0FlZY56EyWpYw1uSo/fi3fa8xj5fCrcXRmMYQvUKN4VUcu/4Nrubrx/jHx9DLhORoqB+pZf2bbdJFqLYYDNq6s=
