language: rust
os:
- linux
- windows
rust:
- stable
jobs:
  allow_failures:
  - rust: nightly
  fast_finish: true
before_install:
- if [ "$TRAVIS_OS_NAME" = "windows" ]; then export LIB="./lib"; fi
install:
- cargo build --release
script:
- cargo test --release
addons:
  apt:
    packages:
    - libsdl2-dev
    - libsdl2-image-dev
    - libsdl2-mixer-dev
    - libsdl2-ttf-dev
before_deploy:
- |-
  FILE_NAME="super-jef-$TRAVIS_TAG-$TRAVIS_OS_NAME"
  if [ "$TRAVIS_OS_NAME" = "windows" ]; then
    mkdir super-jeff
    cp target/release/super-jeff.exe ./super-jeff
    cp -r assets ./super-jeff
    cp lib/*.{dll,txt} ./super-jeff
    ls -l super-jeff
    tar -cavf $FILE_NAME.zip super-jeff
  fi
  if [ "$TRAVIS_OS_NAME" = "linux" ]; then
    tar -C target/release -cvf $FILE_NAME.tar super-jeff
    tar -rf $FILE_NAME.tar assets
    gzip $FILE_NAME.tar
  fi
deploy:
  provider: releases
  file_glob: true
  file:
    - super-jeff*.tar.gz
    - super-jeff*.zip
  skip_cleanup: true
  on:
    tags: true
  api_key:
    secure: QyZ2EXVWtHbeH1emdaA2nz1gGXSLQKqHeqM58vMQQKuY6A4icW2C4VeeQSmfDEpT1bUJcldcgwt5CieJhj5jCBpXhjIFS+9lT+ZQ/SlvM6ygaoLYbHe9n/MK1zAlkvfjk1RHsh7vp2fWcYhTYR3VxtC+OQq5wqqPg77Sp9hisPRJ1sa8IPYAH6NG9tY9SjaK+BS8rxDZEHyKzg/ztc4l8P7ve+aTSVSw32Ee3Q7rdfVZBmporJ5WyI1KoFaCBtxm/mRck7kgBUy8StvuNlIplbQWyLr+B0z+jN4P1nANZNMYJTzRv6p5cyB2w8xBU79qvqfV8JmRieozYpuOSPqq/QirPVQXTawKioFsWv/WLONOuVRYysVwXwuhDd4ufz/YXHyiIiKjY/abiAmcyB3COqbA8ZI8PBcSOlchg337tM9w6ZEFEiTLLwjNnfmJSZ5c01VRW8gS2ju/4hQ8GJ+SGjObI22NxfmGBUqiBuxjfoKynhNy31saswBZ9DPtgZmjSv7Kcr9lrXjcyvhDoXFl5P1l37/lXXB0ED3sXhG2SoCgSaFqDThg3eqJQZK5N7LDujPXKJwvY6p6zgCtlAdJWESSn+eaoYg3OHypD5p3Sae+Qb+4uQKpHWXYf5p18o1+9ukbe9HO+xm5oleluA39/7thVbyGqX5QnMot4TgZfc4=
