language: rust

os:
- linux
- windows

rust:
- stable

jobs:
  allow_failures:
  - rust: nightly
  fast_finish: true

  before_install:
- if [ "$TRAVIS_OS_NAME" = "windows" ]; then export LIB="./lib"; fi

install:
- cargo build --release

script:
- cargo test --release

addons:
  apt:
    packages:
    - libsdl2-dev
    - libsdl2-image-dev
    - libsdl2-mixer-dev
    - libsdl2-ttf-dev

deploy:
  provider: script
  script: ruby deploy.rb
