language: rust

rust:
- stable

os:
- linux
- windows

jobs:
  allow_failures:
  - rust: nightly
  fast_finish: true

before_install:
- if [ "$TRAVIS_OS_NAME" = "windows" ]; then export LIB="./lib"; fi

install:
- cargo build --release

script:
- cargo test --release

addons:
  apt:
    packages:
    - libsdl2-dev
    - libsdl2-image-dev
    - libsdl2-mixer-dev
    - libsdl2-ttf-dev

before_deploy:
- bash package.sh

deploy:
  provider: releases
  file_glob: true
  file:
  - $TRAVIS_BUILD_DIR/super-jeff-*.zip
  - $TRAVIS_BUILD_DIR/super-jeff-*.tar.gz
  skip_cleanup: true
  on:
    tags: true
  api_key:
    secure: QyZ2EXVWtHbeH1emdaA2nz1gGXSLQKqHeqM58vMQQKuY6A4icW2C4VeeQSmfDEpT1bUJcldcgwt5CieJhj5jCBpXhjIFS+9lT+ZQ/SlvM6ygaoLYbHe9n/MK1zAlkvfjk1RHsh7vp2fWcYhTYR3VxtC+OQq5wqqPg77Sp9hisPRJ1sa8IPYAH6NG9tY9SjaK+BS8rxDZEHyKzg/ztc4l8P7ve+aTSVSw32Ee3Q7rdfVZBmporJ5WyI1KoFaCBtxm/mRck7kgBUy8StvuNlIplbQWyLr+B0z+jN4P1nANZNMYJTzRv6p5cyB2w8xBU79qvqfV8JmRieozYpuOSPqq/QirPVQXTawKioFsWv/WLONOuVRYysVwXwuhDd4ufz/YXHyiIiKjY/abiAmcyB3COqbA8ZI8PBcSOlchg337tM9w6ZEFEiTLLwjNnfmJSZ5c01VRW8gS2ju/4hQ8GJ+SGjObI22NxfmGBUqiBuxjfoKynhNy31saswBZ9DPtgZmjSv7Kcr9lrXjcyvhDoXFl5P1l37/lXXB0ED3sXhG2SoCgSaFqDThg3eqJQZK5N7LDujPXKJwvY6p6zgCtlAdJWESSn+eaoYg3OHypD5p3Sae+Qb+4uQKpHWXYf5p18o1+9ukbe9HO+xm5oleluA39/7thVbyGqX5QnMot4TgZfc4=
