language: rust

os:
  - linux
  - windows

rust:
  - stable
  - beta
  - nightly

jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true

before_install:
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then export LIB="./lib"; fi

script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo build --release

addons:
  apt:
    packages:
    - libsdl2-dev
    - libsdl2-image-dev
    - libsdl2-mixer-dev
    - libsdl2-ttf-dev

cache: cargo
